-- Module 03 Account Management
-- PostgreSQL 17 / Neon compatible migration script
-- Reuse-first migration: extends Modules 01/02 schema with account lifecycle tables

BEGIN;

-- Core account master table mapped to existing users table.
CREATE TABLE IF NOT EXISTS accounts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL REFERENCES users(id),
    account_number  VARCHAR(34)  NOT NULL UNIQUE,
    account_type    VARCHAR(30)  NOT NULL,
    currency_code   CHAR(3)      NOT NULL DEFAULT 'INR',
    status          VARCHAR(30)  NOT NULL DEFAULT 'PENDING_APPROVAL',
    opened_at       TIMESTAMP,
    closed_at       TIMESTAMP,
    closed_reason   VARCHAR(255),
    created_by      BIGINT REFERENCES users(id),
    updated_by      BIGINT REFERENCES users(id),
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP,
    CONSTRAINT chk_accounts_type
        CHECK (account_type IN ('SAVINGS', 'CURRENT')),
    CONSTRAINT chk_accounts_status
        CHECK (status IN ('PENDING_APPROVAL', 'ACTIVE', 'FROZEN', 'CLOSED')),
    CONSTRAINT chk_accounts_close_consistency
        CHECK (
            (status <> 'CLOSED' AND closed_at IS NULL)
            OR (status = 'CLOSED')
        )
);

-- Immutable lifecycle timeline for account status changes.
CREATE TABLE IF NOT EXISTS account_status_history (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id   BIGINT       NOT NULL REFERENCES accounts(id),
    from_status  VARCHAR(30),
    to_status    VARCHAR(30)  NOT NULL,
    changed_by   BIGINT       NOT NULL REFERENCES users(id),
    reason       VARCHAR(255),
    metadata     TEXT,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_account_history_status
        CHECK (to_status IN ('PENDING_APPROVAL', 'ACTIVE', 'FROZEN', 'CLOSED'))
);

-- Account list and lookup performance indexes.
CREATE INDEX IF NOT EXISTS idx_accounts_user_created_at
    ON accounts (user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_accounts_status_type_created_at
    ON accounts (status, account_type, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_accounts_currency
    ON accounts (currency_code);

CREATE INDEX IF NOT EXISTS idx_account_status_history_account_created_at
    ON account_status_history (account_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_account_status_history_changed_by_created_at
    ON account_status_history (changed_by, created_at DESC);

COMMIT;

