-- Module 02 Customer Management
-- PostgreSQL 17 / Neon compatible migration script
-- Reuse-first migration: extends Module 01 auth schema, no duplicate customer tables

BEGIN;

-- Optional compliance and KYC review fields on existing customer_profiles table.
ALTER TABLE customer_profiles
    ADD COLUMN IF NOT EXISTS government_id VARCHAR(50),
    ADD COLUMN IF NOT EXISTS government_id_type VARCHAR(30),
    ADD COLUMN IF NOT EXISTS kyc_reviewed_by BIGINT REFERENCES users(id),
    ADD COLUMN IF NOT EXISTS kyc_reviewed_at TIMESTAMP,
    ADD COLUMN IF NOT EXISTS kyc_remarks VARCHAR(255),
    ADD COLUMN IF NOT EXISTS updated_by BIGINT REFERENCES users(id);

-- Soft-delete audit fields for admin lifecycle controls.
ALTER TABLE users
    ADD COLUMN IF NOT EXISTS deleted_by BIGINT REFERENCES users(id),
    ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP;

-- Immutable audit timeline for admin customer actions.
CREATE TABLE IF NOT EXISTS customer_admin_actions (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_user_id  BIGINT       NOT NULL REFERENCES users(id),
    admin_user_id     BIGINT       NOT NULL REFERENCES users(id),
    action_type       VARCHAR(40)  NOT NULL,
    reason            VARCHAR(255),
    before_state      TEXT,
    after_state       TEXT,
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_customer_admin_actions_type
        CHECK (
            action_type IN (
                'PROFILE_UPDATED',
                'KYC_UPDATED',
                'STATUS_UPDATED',
                'SOFT_DELETED',
                'RESTORED'
            )
        )
);

-- Prevent duplicate government identity when present.
CREATE UNIQUE INDEX IF NOT EXISTS uq_customer_profiles_government_id
    ON customer_profiles (government_id)
    WHERE government_id IS NOT NULL;

-- Support common Module 02 filters.
CREATE INDEX IF NOT EXISTS idx_customer_profiles_kyc_status
    ON customer_profiles (kyc_status);

CREATE INDEX IF NOT EXISTS idx_users_not_deleted_role_status
    ON users (is_deleted, role_id, status);

CREATE INDEX IF NOT EXISTS idx_users_deleted_at
    ON users (deleted_at);

CREATE INDEX IF NOT EXISTS idx_customer_admin_actions_customer_created_at
    ON customer_admin_actions (customer_user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_customer_admin_actions_admin_created_at
    ON customer_admin_actions (admin_user_id, created_at DESC);

COMMIT;

