spring:
  datasource:
    url: jdbc:postgresql://ep-silent-wildflower-adbm3wmi-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_c0UTLarlVX4Y
