spring:
  application:
    name: digital-banking

info:
  app:
    name: ${spring.application.name}
    description: Digital Banking Backend Service
    version: 0.0.1-SNAPSHOT

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

app:
  auth:
    jwt-secret: "digital-banking-super-secret-key-for-jwt-signing-256-bits"
    jwt-expiration-seconds: 86400

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
