-- Module 04 Transaction Processing
-- PostgreSQL 17 / Neon compatible migration script
-- Reuse-first migration: extends Modules 01-03 with immutable transaction ledger

BEGIN;

-- Balance ownership for transactional posting logic.
ALTER TABLE accounts
    -- Spendable balance after posted debits/credits.
    ADD COLUMN IF NOT EXISTS available_balance NUMERIC(19,2) NOT NULL DEFAULT 0.00,
    -- Book/ledger balance used for reconciliation views.
    ADD COLUMN IF NOT EXISTS ledger_balance NUMERIC(19,2) NOT NULL DEFAULT 0.00;

-- Immutable ledger table for all postings.
CREATE TABLE IF NOT EXISTS account_transactions (
    -- Surrogate primary key for each ledger entry.
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Account on which this entry is posted.
    account_id             BIGINT        NOT NULL REFERENCES accounts(id),
    -- Unique business reference for the transaction entry.
    transaction_ref        VARCHAR(64)   NOT NULL UNIQUE,
    -- Client-provided de-duplication key for safe retries.
    idempotency_key        VARCHAR(80),
    -- Business transaction category.
    transaction_type       VARCHAR(30)   NOT NULL,
    -- Accounting side of the entry: debit or credit.
    entry_side             VARCHAR(10)   NOT NULL,
    -- Monetary value posted in this entry.
    amount                 NUMERIC(19,2) NOT NULL,
    -- ISO-like currency code for amount and balances.
    currency_code          CHAR(3)       NOT NULL,
    -- Account balance immediately before posting this entry.
    balance_before         NUMERIC(19,2) NOT NULL,
    -- Account balance immediately after posting this entry.
    balance_after          NUMERIC(19,2) NOT NULL,
    -- Counterparty account for transfers (nullable for cash-like ops).
    counterparty_account_id BIGINT REFERENCES accounts(id),
    -- Shared reference to link debit+credit entries of one transfer.
    transfer_group_ref     VARCHAR(64),
    -- Posting lifecycle status of this ledger entry.
    status                 VARCHAR(20)   NOT NULL DEFAULT 'POSTED',
    -- Optional operator/customer remarks for audit context.
    description            VARCHAR(255),
    -- User who initiated or executed the posting.
    created_by             BIGINT        NOT NULL REFERENCES users(id),
    -- Timestamp when entry was persisted.
    created_at             TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_account_transactions_type
        CHECK (transaction_type IN ('DEPOSIT', 'WITHDRAWAL', 'TRANSFER', 'ADJUSTMENT', 'REVERSAL')),
    CONSTRAINT chk_account_transactions_entry_side
        CHECK (entry_side IN ('DEBIT', 'CREDIT')),
    CONSTRAINT chk_account_transactions_amount
        CHECK (amount > 0),
    CONSTRAINT chk_account_transactions_status
        CHECK (status IN ('POSTED', 'REVERSED'))
);

CREATE INDEX IF NOT EXISTS idx_account_transactions_account_created_at
    ON account_transactions (account_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_account_transactions_idempotency_account
    ON account_transactions (idempotency_key, account_id)
    WHERE idempotency_key IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_account_transactions_transfer_group
    ON account_transactions (transfer_group_ref)
    WHERE transfer_group_ref IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_account_transactions_created_by_created_at
    ON account_transactions (created_by, created_at DESC);

COMMIT;

